### ISSUE TITLE
I am getting the issue timeout

### ISSUE THREAD

**Issue by vivekgs2007** [darul75/satelize#1]
Hello,
I am geeting the issue timeout error.

Error: timeout
    at ClientRequest.<anonymous> (../../,../node_modules/satelize/lib/satelize.js:1:627)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:104:17)
    at Socket.emitTimeout (_http_client.js:536:10)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:104:17)
    at Socket._onTimeout (net.js:340:8)
    at _makeTimerTimeout (timers.js:467:11)
    at Timer.unrefTimeout (timers.js:531:5)

I am able to fix the issue by increasing the timeout value 10000, in src/satelize can't it can be configurable by user end

**Comment by darul75** [comment]
sure @vivekgs2007 I will see what can be improved

**Comment by darul75** [comment]
done in https://github.com/darul75/satelize/releases/tag/v0.1.1 with "timeout" attribute option
