### ISSUE TITLE
TypeError: Cannot read property 'iso_code' of undefined 

### ISSUE THREAD

**Issue by vkupar** [darul75/satelize#8]
TypeError: Cannot read property 'iso_code' of undefined
at Satelize.satelize (/var/app/current/node_modules/satelize/src/satelize.js:42:33)
at module.exports.test (/var/app/current/test/file.js:109:14)
at Layer.handle [as handle_request] (/var/app/current/node_modules/express/lib/router/layer.js:82:5)
at trim_prefix (/var/app/current/node_modules/express/lib/router/index.js:302:13)
at /var/app/current/node_modules/express/lib/router/index.js:270:7
at Function.proto.process_params (/var/app/current/node_modules/express/lib/router/index.js:321:12)
at next (/var/app/current/node_modules/express/lib/router/index.js:261:10)
at next (/var/app/current/node_modules/express/lib/router/route.js💯14)
at next (/var/app/current/node_modules/express/lib/router/route.js:104:14)
at next (/var/app/current/node_modules/express/lib/router/route.js:104:14)
at next (/var/app/current/node_modules/express/lib/router/route.js:104:14)
at next (/var/app/current/node_modules/express/lib/router/route.js:104:14)
at next (/var/app/current/node_modules/express/lib/router/route.js:104:14)
at next (/var/app/current/node_modules/express/lib/router/route.js:104:14)
at next (/var/app/current/node_modules/express/lib/router/route.js:104:14)
at next (/var/app/current/node_modules/express/lib/router/route.js:104:14)

**Comment by hacker** [comment]
Seen this one too for `80.231.217.6`. If that helps to reproduce. Though I think it's just about checking for `country` before accessing its properties. Hope that helps (not the wise advice, but the ip address for reproducing:)).
